
#################
### AUTOSTART ###
#################

exec-once = ~/.config/hypr/scripts/hyprlock-gen.sh
exec-once = awww-daemon
exec-once = ~/.config/waybar/launch.sh
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = swaync
exec-once = hypridle
exec-once = ~/.config/hypr/scripts/wallpaper-restore.sh
exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = nwg-look -a   # applies stored gsettings on login
exec-once = swayosd-server
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
