#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════
#  hyprlock-gen.sh
#  Reads the active monitor resolution, computes independent X and
#  Y scale factors (handles 16:9 vs 16:10 and any other ratio),
#  then writes a complete layout config to:
#    ~/.cache/arcos/hyprlock-dynamic.conf
#  which hyprlock.conf sources on every lock.
#
#  Runs automatically at Hyprland startup via autostart.conf.
#  Re-run manually after changing resolution:
#    ~/.config/hypr/scripts/hyprlock-gen.sh
# ══════════════════════════════════════════════════════════════════

# Brief wait on startup so hyprctl is ready
[[ "${1}" != "--now" ]] && sleep 1.5

# ── Read logical resolution (accounts for monitor scale factor) ───
read -r W H < <(
    hyprctl monitors -j 2>/dev/null | python3 -c "
import json, sys
mons = json.load(sys.stdin)
m = next((x for x in mons if not x.get('disabled', False)), mons[0])
sc = float(m.get('scale', 1.0))
print(round(m['width'] / sc), round(m['height'] / sc))
" 2>/dev/null
)

# Fallback to base resolution if hyprctl is unavailable
W=${W:-1440}
H=${H:-900}

# ── Base values (1440×900) ────────────────────────────────────────
BASE_W=1440
BASE_H=900

# ── Independent scale on each axis ───────────────────────────────
# This is the key: 1440→1920 gives SX=1.333, 900→1080 gives SY=1.2
# Using them separately preserves the design's proportions on any
# aspect ratio, unlike a single uniform scale.
SX=$(awk "BEGIN { printf \"%.4f\", ${W} / ${BASE_W} }")
SY=$(awk "BEGIN { printf \"%.4f\", ${H} / ${BASE_H} }")

# ── Scale helpers ─────────────────────────────────────────────────
sx() { awk "BEGIN { printf \"%d\", int($1 * ${SX} + 0.5) }"; }
sy() { awk "BEGIN { printf \"%d\", int($1 * ${SY} + 0.5) }"; }

# ── Compute all values ────────────────────────────────────────────

# Font sizes follow height (vertical rhythm is more sensitive to Y)
FONT_LARGE=$(sy 120)
FONT_AMPM=$(sy 18)
FONT_DATE=$(sy 15)

# Vertical positions (offset from screen center, valign=center)
POS_HOUR_Y=$(sy 100)
POS_MIN_Y=$(sy -40)
POS_AMPM_Y=$(sy 30)
POS_DATE_Y=$(sy -155)
POS_INPUT_Y=$(sy -230)

# Horizontal positions (offset from screen center, halign=center)
POS_AMPM_X=$(sx 160)

# Input field dimensions — each axis scales independently
INPUT_W=$(sx 280)
INPUT_H=$(sy 48)

# ── Write dynamic config ──────────────────────────────────────────
mkdir -p ~/.cache/arcos

cat > ~/.cache/arcos/hyprlock-dynamic.conf << CONF
# ════════════════════════════════════════════════════════
# AUTO-GENERATED by hyprlock-gen.sh — do not edit manually
# Resolution : ${W}×${H}  |  SX=${SX}  SY=${SY}
# Regenerate : ~/.config/hypr/scripts/hyprlock-gen.sh
# ════════════════════════════════════════════════════════

# ── Hour ─────────────────────────────────────────────────────────
label {
    monitor     =
    text        = cmd[update:1000] echo "\$(date +'%I')"
    color       = rgba(86, 140, 102, 0.95)
    font_size   = ${FONT_LARGE}
    font_family = Orbitron Bold
    position    = 0, ${POS_HOUR_Y}
    halign      = center
    valign      = center
}

# ── Minutes ───────────────────────────────────────────────────────
label {
    monitor     =
    text        = cmd[update:1000] echo "\$(date +'%M')"
    color       = rgba(191, 167, 115, 0.95)
    font_size   = ${FONT_LARGE}
    font_family = Orbitron Bold
    position    = 0, ${POS_MIN_Y}
    halign      = center
    valign      = center
}

# ── AM/PM ─────────────────────────────────────────────────────────
label {
    monitor     =
    text        = cmd[update:1000] echo "\$(date +'%p')"
    color       = rgba(255, 255, 255, 0.35)
    font_size   = ${FONT_AMPM}
    font_family = Orbitron
    position    = ${POS_AMPM_X}, ${POS_AMPM_Y}
    halign      = center
    valign      = center
}

# ── Date ──────────────────────────────────────────────────────────
label {
    monitor     =
    text        = cmd[update:60000] echo "\$(date +'%A, %B %d')"
    color       = rgba(255, 255, 255, 0.35)
    font_size   = ${FONT_DATE}
    font_family = Inter
    position    = 0, ${POS_DATE_Y}
    halign      = center
    valign      = center
}

# ── Password input ────────────────────────────────────────────────
input-field {
    monitor           =
    size              = ${INPUT_W}, ${INPUT_H}
    outline_thickness = 2
    dots_size         = 0.25
    dots_spacing      = 0.20
    dots_center       = true
    dots_rounding     = -1

    outer_color       = rgba(255, 255, 255, 0.10)
    inner_color       = rgba(29, 27, 24, 0.80)
    font_color        = rgba(255, 255, 255, 0.90)
    fade_on_empty     = true
    fade_timeout      = 1000
    placeholder_text  = <span foreground="##ffffff66">󰌾  Enter Password</span>

    check_color       = rgba(83, 103, 84, 0.90)
    fail_color        = rgba(180, 60, 60, 0.90)
    fail_text         = <span foreground="##ff6e6e">  Wrong password</span>

    rounding          = 12
    position          = 0, ${POS_INPUT_Y}
    halign            = center
    valign            = center
}
CONF

echo "hyprlock-gen: config written for ${W}×${H} (SX=${SX}, SY=${SY})"
