include wallust-colors.conf

font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font Bold
italic_font      FiraCode Nerd Font Italic
font_size        12.0

background_opacity 0.7
window_padding_width 12
