$background = rgb(101114)
$foreground = rgb(EEEFF7)
$color0  = rgb(38393C)
$color1  = rgb(292B0C)
$color2  = rgb(513D52)
$color3  = rgb(616758)
$color4  = rgb(625EA9)
$color5  = rgb(936568)
$color6  = rgb(9A9CAD)
$color7  = rgb(DEDFEB)
$color8  = rgb(9B9CA4)
$color9  = rgb(363A10)
$color10 = rgb(6C516D)
$color11 = rgb(828975)
$color12 = rgb(837DE1)
$color13 = rgb(C4868A)
$color14 = rgb(CED0E7)
$color15 = rgb(DEDFEB)